version: 2

project_name: verkcli

release:
  github:
    owner: ChrisVo
    name: verkcli

before:
  hooks:
    - go mod tidy

builds:
  - id: verkcli
    main: ./cmd/verkcli
    binary: verkcli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X verkcli/internal/cli.version={{.Version}}
      - -X verkcli/internal/cli.commit={{.Commit}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: false

brews:
  - name: verkcli
    directory: Formula
    homepage: https://github.com/ChrisVo/verkcli
    description: "Inspect cameras, fetch thumbnails, and script Verkada APIs"
    install: |
      bin.install "verkcli"
    test: |
      system "#{bin}/verkcli", "version"
    repository:
      owner: ChrisVo
      name: homebrew-tap
      branch: main
      # Create a classic PAT with access to the tap repo and add it as a GitHub Actions secret.
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
